collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9910395
  brandStrength: 1
  lightness: 0.7401434
  brandColors:
    - '#FFFFFF'
    - '#D0D0D0'
    - '#9B9B9D'
    - '#000000'
    - '#636363'
  rhythmicContrast: 0.5645161
typography_spectrum: 0.7831541
layout_spectrum: 1
name: Little Chief
